### ISSUE TITLE
php artisan dusk:dashboard Error

### ISSUE THREAD

**Issue by stonkeep** [beyondcode/dusk-dashboard#15]
When I run `php artisan dusk:dashboard`
I recive the followed error

  ErrorException  : simplexml_load_file(): I/O warning : failed to load external entity "file:/C:/SGP-Laravel/phpunit.dusk.xml"

  at C:\SGP-Laravel\vendor\beyondcode\dusk-dashboard\src\Console\StartDashboardCommand.php:94
    90|     }
    91|
    92|     protected function getTestSuitePath()
    93|     {
  > 94|         $xml = simplexml_load_file(base_path('phpunit.dusk.xml'));
    95|
    96|         $directories = [];
    97|
    98|         foreach ($xml->testsuites->testsuite as $testsuite) {

  Exception trace:

  1   simplexml_load_file("C:\SGP-Laravel\phpunit.dusk.xml")
      C:\SGP-Laravel\vendor\beyondcode\dusk-dashboard\src\Console\StartDashboardCommand.php:94

  2   BeyondCode\DuskDashboard\Console\StartDashboardCommand::getTestSuitePath()
      C:\SGP-Laravel\vendor\beyondcode\dusk-dashboard\src\Console\StartDashboardCommand.php:72

  Please use the argument -v to see more details.

**Comment by mpociot** [comment]
Hm. Looks like you don’t have a phpunit.dusk.xml file in your root path. 
The package currently needs this file. I’ll change the default behavior so that it falls back to the default test directory. 

You can simply copy this file as phpunit.dusk.cml in the meantime. 

https://github.com/laravel/dusk/blob/4.0/stubs/phpunit.xml
