### ISSUE TITLE
Dusk Dashboard on docker

### ISSUE THREAD

**Issue by tomaszd7** [beyondcode/dusk-dashboard#53]
I am working on Laravel 5.7 application built on docker (docker-compose). Several containers with nginx and php kept as separate containers. I may run Laravel dusk tests on php container, however I am changing APP_URL into container internal server name. 
Is it possible Dusk Dashboard to be run on docker containers?
My first issue is to forward 9773 port outside docker into browser to see dashboard views but no success so far.

**Comment by giannirx** [comment]
I'm having the same issue. after following the simple instructions to require and changing DustTest file, I have to go in my url and change it to 127.0.0.1 instead of our normal url where we have our dev environment. I'm wondering if you got it working with Docker by any chance and what steps would I have to take?

**Comment by lfrichter** [comment]
I am also having the same difficulty, if there is any solution it would be great. In my case also published on port 9773 but nothing appears.
